spring.application.name=lab3_studentsmanager
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=bao123bao
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false

